# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [9]:
#todo: 
lista = [0,1,2,3,4,5,6,7,8,9]
array = np.array(lista)
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [8]:
#todo:
array_ceros = np.zeros(5)
print(array_ceros)

array_ceros[2] = 5
print(array_ceros)

[0. 0. 0. 0. 0.]
[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [12]:
#todo: 
rand_array = np.random.randint(0,2,(3,3))
print(rand_array)

[[1 1 0]
 [1 0 0]
 [0 0 0]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [28]:
#todo:
arr = np.array([10, 20, 30, 40, 50])
sum_array = arr + 5
print(sum_array)

random_mult = np.random.randint(1, 100)
print(random_mult)

mult_array = np.multiply(sum_array, random_mult)
print(mult_array)

[15 25 35 45 55]
30
[ 450  750 1050 1350 1650]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [29]:
#todo:
print(np.eye(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [38]:
#todo: 
array_op = np.arange(0, 21, 2)
print(array_op)

suma = np.add(array_op, 2)
print("suma:", suma)

resta = np.subtract(array_op, 15)
print("resta:", resta)

multiplicacion = np.multiply(array_op, 4)
print("multiplicacion:", multiplicacion)

div = np.divide(array_op, 2)
print("division:", div)




[ 0  2  4  6  8 10 12 14 16 18 20]
suma: [ 2  4  6  8 10 12 14 16 18 20 22]
resta: [-15 -13 -11  -9  -7  -5  -3  -1   1   3   5]
multiplicacion: [ 0  8 16 24 32 40 48 56 64 72 80]
division: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
